name: Rails CI/CD with RuboCop, Docker, and Cypress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILS_ENV: development
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/haiku-designs:latest

jobs:
  lint-and-db-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install rails dependencies
        run: bundle install
        

      - name: Set up SQLite database
        run: |
          cp config/database.yml.ci config/database.yml
          mkdir -p storage
          rm -f storage/development.sqlite3
          touch storage/development.sqlite3
          bundle exec rails db:schema:load

      - name: Run RuboCop
        run: bundle exec rubocop

  docker-build-push:
    needs: lint-and-db-setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

  e2e-tests:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install JavaScript dependencies
        run: npm install
        
      - name: Pull and run Docker container
        run: |
          docker pull $DOCKER_IMAGE
          docker run -d -p 3000:3000 $DOCKER_IMAGE
          sleep 10

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          browser: chrome
